### ISSUE TITLE
Is it possible to have tagged groups, or multiple tag types on the same model?

### ISSUE THREAD

**Issue by joakim-emagine** [dereuromark/cakephp-tags#20]
So for example,
Model A
Group 1 - tags = A,B,C
Group 2 - tags = 1,2,3,4

And in turn, one would have two separate fields in the view, one for each group. Is this possible currently?

**Comment by dereuromark** [comment]
I believe this should be possible using "namespace" config
https://github.com/dereuromark/cakephp-tags/blob/master/src/Model/Behavior/TagBehavior.php#L27

Please see if that helps, and maybe you can help improving the docs for this part then.

I think that for this to work you might have to attach the behavior then twice, each with its own field/namespace config.

**Comment by joakim-emagine** [comment]
@dereuromark Thanks! Will try this, and will let you know what we find.

**Comment by joakim-emagine** [comment]
Getting the error: 
```
The "Tag" alias has already been loaded with the following config
```
I'm guessing because cakePHP doesn't allow adding the same behavior at the same time.

**Comment by dereuromark** [comment]
You need aliasing here, yeah.

**Comment by joakim-emagine** [comment]
Aliasing the plugin itself?  the below config throws the error:

```
        $this->addBehavior('Tags.Tag', [
            'tagsAlias' => 'ReviewTags',
            'taggedAlias' => 'ReviewTagged',
            'field'=>'review_list',
            'tagsCounter'=>false,
            'taggedCounter' => false,
            'namespace' => 'Review'
        ]);

        $this->addBehavior('Tags.Tag', [
            'tagsAlias' => 'Tags',
            'taggedAlias' => 'Tagged',
            'tagsCounter'=>false,
            'taggedCounter' => false,
            'namespace' => 'Tags',
            'field'=>'tag_list'
        ]);
```

**Comment by dereuromark** [comment]
Should be documented in core docs:

    ->addBehavior('Alias', ['className' => 'Tags.Tag', ...])

**Comment by joakim-emagine** [comment]
> Should be documented in core docs:
> 
> ```
> ->addBehavior('Alias', ['className' => 'Tags.Tag', ...])
> ```

Great ! This worked! I have been looking all over for this syntax.

Not in core documentation though:
https://api.cakephp.org/3.6/source-class-Cake.ORM.Table.html#841-870
https://book.cakephp.org/3.0/en/orm/behaviors.html#

Thanks !!

**Comment by dereuromark** [comment]
Oh geeze, you could make a docs PR here  to help others (both core and here).

**Comment by dereuromark** [comment]
How did you manage to have multiple tags without wiping out the others?
I tried to write a test case and found some issues with the current code.

**Comment by dereuromark** [comment]
Can you see if the current code might still be broken?
And if https://github.com/dereuromark/cakephp-tags/pull/24 fully fixes things?
That way, you dont even need different "namespaces", it works even without them.

**Comment by joakim-emagine** [comment]
> How did you manage to have multiple tags without wiping out the others?
> I tried to write a test case and found some issues with the current code.

Sorry, I missed this. It works for me, however, I noticed in the database each time the model is saved, new tagged rows are created in the 'tags_tags' table. Also, noticing now 'slugs' are not being saved although 'cakephp-tools' plugin is loaded.

**Comment by dereuromark** [comment]
This should be fixed with latest master. Slugging is now done differently.
