### ISSUE TITLE
accessible property

### ISSUE THREAD

**Issue by asgraf** [dereuromark/cakephp-tags#21]
In both files :
https://github.com/dereuromark/cakephp-tags/blob/master/src/Model/Entity/Tag.php#L22
https://github.com/dereuromark/cakephp-tags/blob/master/src/Model/Entity/Tagged.php#L22

there is `public $accessible` property instead of `protected $_accessible` property.
This causes EntityRoute to generate url with following query string attached to a generated route `?_entity[accessible][*]=0&_entity[accessible][label]=1`

**Comment by dereuromark** [comment]
Thank you, are you able to provide a quick PR to fix this?

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-tags/commit/4f7bdd833259aa95a6c748b0c3da2fd655912bdc

**Comment by dereuromark** [comment]
Does the current dev-master version fix your issues? Then I can tag a patch release.

**Comment by dereuromark** [comment]
Also, would you be able to provide a PR with some docs on how to make EntityRoute work with this plugin and tags?
That would be awesome.

If you want to keep it quicker, you can also just drop all the info here, and I can make docs from it, and maybe even provide some test cases for it.

**Comment by asgraf** [comment]
> Does the current dev-master version fix your issues? Then I can tag a patch release.

Yes, it fixed the problem.

**Comment by dereuromark** [comment]
Some insights into how you made EntityRoute work with this plugin would be awesome to know.

**Comment by asgraf** [comment]
Here is source code of my hobby project i'm working on my free time:
https://github.com/asgraf/1polska/
I'm using your plugin there for tagging Postulates & Representatives

1) I have added the appropriate routing for tags
https://github.com/asgraf/1polska/blob/master/config/routes.php#L123

2) Created custom TagsController with view action
https://github.com/asgraf/1polska/blob/master/src/Controller/TagsController.php#L29

3) Contained Tags in Postulates::view action
https://github.com/asgraf/1polska/blob/master/src/Controller/PostulatesController.php#L216

4) And then linked tags in ctp file:
https://github.com/asgraf/1polska/blob/master/src/Template/Postulates/view.ctp#L75
