### ISSUE TITLE
Suggestion: Use uuid instead of integer for  foreign key

### ISSUE THREAD

**Issue by ghost** [dereuromark/cakephp-tags#29]
In the table `tags_tagged` there is a column `fk_id` the foreign key
that is currently of type `integer (11)`.
This way it is not possible to attach tags to models that have a uuid as id.

As the column `fk_id` is not hard linked to any other table, we should be able
to change it to `uuid` and it should work with uuids as well as integers.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-tags/tree/master/docs#uuids

**Comment by ghost** [comment]
Yes that is correct, but this clearly states the primary key of the tags.
This step is optional `If you, for some reason, still need to use UUIDs,`.
It is mandatory if you want to tag at least one model that contains an UUID.
The current documentation does not represent this in my opinion

I created a small PR:
https://github.com/dereuromark/cakephp-tags/pull/30
