### ISSUE TITLE
Copyright info / attribution to muffin/tags missing.

### ISSUE THREAD

**Issue by ADmad** [dereuromark/cakephp-tags#3]
Since this plugin is based off [muffin/tags](https://github.com/UseMuffin/Tags) and still contains a lot of the original code it would be prudent to keep the copyright of original plugin or at least add an attribution link in your readme/license file.

**Comment by dereuromark** [comment]
It does. also see composer.json.
The license Block was invalid (missing mit license Header MIT) by the way.

**Comment by dereuromark** [comment]
the license Block was invalid (missing mit license Header MIT) by the way.

**Comment by dereuromark** [comment]
Personally I find the composer and thus packagist linking more relevant and visible.
https://packagist.org/packages/dereuromark/cakephp-tags
But it probably wouldnt hurt to readd the name in  license file instead of completely replacing.

**Comment by dereuromark** [comment]
Resolved with https://github.com/dereuromark/cakephp-tags/commit/f170c8725c0848820f4ca87a393717e925779966 ?

**Comment by ADmad** [comment]
Thanks.
