### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by rudy1976s** [dereuromark/cakephp-tags#38]
Hi Mark
Do you think is possible to attach the translate behavior to Tags plugin ? I would need to be able to  translate tags in up to 5 language and display all in a tab like the following using select 2 as in your example ?

![tags](https://user-images.githubusercontent.com/1161343/87880750-7d52c100-c9f4-11ea-8466-3cd1f8451ef4.png)

Thank you in advance

Rudy

**Comment by dereuromark** [comment]
Try it and let me know how it goes.
Maybe we can add some docs here.
