### ISSUE TITLE
fk_model is not being automatically assigned

### ISSUE THREAD

**Issue by MMUmedaGIT** [dereuromark/cakephp-tags#6]
I must be missing something very obvious here. The tags are saved, the associated tagged are saved as well, except it doesn't assign 'fk_model'. Must I do that manually somewhere?

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-tags/blob/master/src/Model/Behavior/TagBehavior.php#L309 is doing that

how are you using the behavior?

**Comment by dereuromark** [comment]
I added a test to be sure: https://github.com/dereuromark/cakephp-tags/commit/3839a3c4f6ff6262c6eae8866f2665597c3ff059#diff-33b2925318abc4cc41b83442ae327efbR75

Also note the exception I added to clarify misuse. But I suspect that your issue is a different one.
It will need more details, though.

**Comment by MMUmedaGIT** [comment]
I'm following your demo exactly, but I'm sending request via ajax instead of regular post, could that be the reason?
 

(btw, thanks for the reply and good job for all your great plugins, man!)

**Comment by dereuromark** [comment]
No, the data coming in doesn't matter.
Can you post that request->data() here, how the structure looks like?
Also your DB tables and the Tags plugin setup?

**Comment by MMUmedaGIT** [comment]
This is what I'm sending to my controller:
![screenshot 2018-03-03 11 58 19](https://user-images.githubusercontent.com/5360677/36935751-4f0e6618-1eda-11e8-99d9-a6c03e082370.png)

This is what I'm getting after patchEntity:
 (notice, no "fk_model" assigned)
![screenshot 2018-03-03 11 58 03](https://user-images.githubusercontent.com/5360677/36935757-6360e104-1eda-11e8-8e53-05dd4f3593ee.png)

**Comment by dereuromark** [comment]
Why are you sending the tags as array instead of a simple list as comma separated string? When they are an array they wont be formatted into the result anymore, then you have to do everything manually.

**Comment by MMUmedaGIT** [comment]
If I add the fk_model directly to the database, it works and the tagged are recognized. 

I'm sending them as array because some will be newly added, others from db.

**Comment by MMUmedaGIT** [comment]
How can I discriminate between old tags and newly created ones?

**Comment by dereuromark** [comment]
If you do it this way you really need to do it manually.

> How can I discriminate between old tags and newly created ones?

You dont have to. The behavior expects the full set and auto-merges (see tests).

It also expects it in the `tag_list` key btw, and as array this would be allowed (see tests):

	'tag_list' => [
		'foo',
		'bar',
	],

Using the `tags` key completely skips the behavior here.

So you are probably doing more logic in the view than necessary.
But you can do it, just check on the presence of a primary key in the tagged/tag elements and based on that add more data.

You are also welcome to provide a PR that would include what you want to do in the behavior.
That would allow for more complex use cases, e.g. adding more attributes in the tags or tagged table.

**Comment by MMUmedaGIT** [comment]
Yes, you're right. I am adding more logic than the basic setup, because of other requirements, but I think I understand what you're saying. Let me try a simple array. I'll post results. Thanks.

**Comment by MMUmedaGIT** [comment]
Oh, but, yeah, if I wanted to add fk_model manually, how would I do that?

**Comment by dereuromark** [comment]
The first link I posted (even though off now due to changes I made in master) shows it: https://github.com/dereuromark/cakephp-tags/blob/master/src/Model/Behavior/TagBehavior.php#L314

    $this->config('fkModelField') => $this->_table->alias()

inside of the behavior has to be called from the outside then

    'fk_model' => $this->MyTable->alias() 

should suffice.

**Comment by MMUmedaGIT** [comment]
Yes, it's working! You're right, a simple array would suffice! :)
