### ISSUE TITLE
Integration with select2

### ISSUE THREAD

**Issue by MMUmedaGIT** [dereuromark/cakephp-tags#8]
Could you help me integrate the matcher in select2 and your plugin, so that the search will include ALL tags and not just the tags belonging to that particular item?

**Comment by dereuromark** [comment]
Sure, we can try sth here, just open a branch for the cakephp-sandbox and start hack-implementing it there so we can both contribute. A new action for the tags plugin

**Comment by MMUmedaGIT** [comment]
But was that your intention, to implement this in the future? Because, obviously, it would make more sense if the search included all tags available...

**Comment by dereuromark** [comment]
I agree with you, but we should have a sandbox demo to work with in order to figure it out.
otherwise - without concrete implementation - it will be hard to verify.

**Comment by MMUmedaGIT** [comment]
Sorry, man, I've never opened a branch on my own, I don't wanna mess it up.

But here's some info that might help:

from select2:

==Select2 will pass each option as represented by its internal representation into this callback to determine if it should be displayed:
```
function matchCustom(params, data) {
    // If there are no search terms, return all of the data
    if ($.trim(params.term) === '') {
      return data;
    }

    // Do not display the item if there is no 'text' property
    if (typeof data.text === 'undefined') {
      return null;
    }

    // `params.term` should be the term that is used for searching
    // `data.text` is the text that is displayed for the data object
    if (data.text.indexOf(params.term) > -1) {
      var modifiedData = $.extend({}, data, true);
      modifiedData.text += ' (matched)';

      // You can return modified objects from here
      // This includes matching the `children` how you want in nested data sets
      return modifiedData;
    }

    // Return `null` if the term should not be displayed
    return null;
}

$(".js-example-matcher").select2({
  matcher: matchCustom
});
```
==
and:


Select2 can render programmatically supplied data from an array or remote data source (AJAX) as dropdown options. In order to accomplish this, Select2 expects a very specific data format. This format consists of a JSON object containing an array of objects keyed by the results key.
```
{
  "results": [
    {
      "id": 1,
      "text": "Option 1"
    },
    {
      "id": 2,
      "text": "Option 2"
    }
  ],
  "pagination": {
    "more": true
  }
}
```

**Comment by dereuromark** [comment]
You can just fork https://github.com/dereuromark/cakephp-sandbox and create your own branch and make a PR.
All code is inside https://github.com/dereuromark/cakephp-sandbox/tree/3.0/plugins/Sandbox/

**Comment by MMUmedaGIT** [comment]
Which branch name (version) should I use for the new branch?

**Comment by dereuromark** [comment]
totally up to you, you can also keep the master one on your fork.

**Comment by MMUmedaGIT** [comment]
Ok, so, fork created... where do we go from here?

**Comment by MMUmedaGIT** [comment]
I can't find the Tags plugin in your Sandbox, Mark...

**Comment by dereuromark** [comment]
Above I gave you all info.
If you then go into the plugin, you see https://github.com/dereuromark/cakephp-sandbox/blob/3.0/plugins/Sandbox/src/Controller/TagsController.php

and the tags code itself of course is in vendor as dependency.

and it will on your local dev then be `http://sandbox.dereuromark.de/sandbox/tags` => `http://sandbox.local/sandbox/tags` etc

**Comment by dereuromark** [comment]
Did you find a working demo here?

See also select2 demo @ https://sandbox.dereuromark.de/sandbox/tags/select
