### ISSUE TITLE
Missing deleteTagsOnEmptyField setting

### ISSUE THREAD

**Issue by mikerogerz** [dereuromark/cakephp-tags#9]
Referring to the now deprecated CakeDC/tags plugin, there was a setting for deleting all associated tags when the input is emptied. With the current implementation, the existing tags are left alone by default. Are there plans to implement similar functionality? Or if there's an alternative solution in mind?

Thanks for all your work on these various CakePHP plugins.

**Comment by dereuromark** [comment]
This sounds like a small improvement or cleanup.
can you make a pr here?

**Comment by mikerogerz** [comment]
Sure no problem.

**Comment by mikerogerz** [comment]
Out of curiosity, why is this the default behaviour? Doesn't it make more sense that the associated tags (if any exist) should be removed if the field exists in the form and is empty? Am I missing something?

https://github.com/dereuromark/cakephp-tags/blob/6cb06062fd33805298b5b5c3697e31c0481d2afc/src/Model/Behavior/TagBehavior.php#L113-L115

**Comment by dereuromark** [comment]
You are right, this is a bug, and now fixed via https://github.com/dereuromark/cakephp-tags/commit/6d3ab3803fa809ba184570deea1fc8b9ebd3f2c4
Thanks for reporting!
